
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const AUTH_ERROR = 'AUTH_ERROR';

const CURRENT_USER_SUCCESS = 'USER_SUCCESS';

const FETCH_LOADING = 'FETCH_LOADING';

const SET_TOKEN = 'SET_TOKEN';

const UPLOAD_HOUSE_IMAGE = 'UPLOAD_HOUSE_IMAGE';
const UPLOAD_ERROR = 'UPLOAD_ERROR';

const NEW_HOUSE_SUCCESS = 'NEW_HOUSE_SUCCESS';
const ALL_HOUSES_SUCCESS = 'ALL_HOUSES_SUCCESS';
const HOUSE_ERROR = 'HOUSE_ERROR';

export {
  SIGNUP_SUCCESS,
  FETCH_LOADING,
  AUTH_ERROR,
  SET_TOKEN,
  LOGIN_SUCCESS,
  NEW_HOUSE_SUCCESS,
  ALL_HOUSES_SUCCESS,
  HOUSE_ERROR,
  CURRENT_USER_SUCCESS,
  UPLOAD_HOUSE_IMAGE,
  UPLOAD_ERROR,
}